spring:
  datasource:
    url: jdbc:mysql://flightrsvdb.cxnuarwowrnu.us-east-1.rds.amazonaws.com:3306/flight-reservation
  jpa:
    hibernate:
      ddl-auto: update
sms:
  url: http://localhost:8090/api/v1/sms/send
email:
  url: http://localhost:8090/api/v1/email/send